### ISSUE TITLE
Proposal to remove the "Post MVP" Zenhub column

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/rdss-handbook#206]
I am sorry if this is too forward, however, to the best of my recollection, this column has not been actively used during sprint planning meetings for some months now. Unless this is incorrect, or others object and desire to use this actively in the future, I would please propose that `Post MVP` simply be removed.

**Comment by bess** [comment]
I really appreciate the thought you're putting into our development process, thank you! I agree that we should remove the "done" column -- it seems redundant to me. 
However, I think it is useful to have a place to put tickets to make it clear that we are not planning to work on them in the near term. Even though we do not look at those tickets during sprint planning, we're always going to get many more feature requests than we can actually address. Giving someone an outlet to write a ticket and putting that ticket somewhere (even if it's in a place like an "icebox" column) seems useful to me. Where would these tickets go otherwise? I would not want to put them into "product backlog" because they are not necessarily things that we as a team want to commit to ever doing.

**Comment by carolyncole** [comment]
We have been utilizing the tickets in this column for work for the students.

**Comment by kelynch** [comment]
Can we revisit this topic and come to a consensus?  I'll add it to the stand-up agenda.

**Comment by kelynch** [comment]
Consensus: let's keep this column as we're using it to work with students and stakeholders.
